workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.financeapp"
      groups:
        - keystore_credentials
      scripts:
        - name: Install dependencies
          script: flutter pub get
        - name: Build release APK
          script: |
            echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
            flutter build apk --release \
              --dart-define=KEYSTORE_PATH=/tmp/keystore.jks \
              --dart-define=KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD \
              --dart-define=KEY_ALIAS=$CM_KEY_ALIAS \
              --dart-define=KEY_PASSWORD=$CM_KEY_PASSWORD
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
