workflows:
  android_debug_apk:
    name: Android Debug APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Flutter versiyasini ko‘rish
        script: flutter --version

      - name: Agar platforma papkalari yo‘q bo‘lsa, yaratish
        script: |
          if [ ! -f "android/app/build.gradle" ]; then
            flutter create .
          fi

      - name: Paketlarni o‘rnatish
        script: flutter pub get

      - name: Debug APK build
        script: flutter build apk --debug
        # Agar release APK xohlasangiz:
        # script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      # Agar release bo‘lsa:
      # - build/app/outputs/flutter-apk/app-release.apk
